# Generated by Django 3.0.8 on 2020-07-31 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('PUBG', "PlayerUnknown's Battlegrounds"), ('CSGO', 'Counter-Strike: Global Offensive'), ('GTAV', 'Grand Theft Auto V'), ('VALR', 'Valorant'), ('RAIN', 'Rainbow Six Siege')], max_length=4)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('is_full', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('PUBG', "PlayerUnknown's Battlegrounds"), ('CSGO', 'Counter-Strike: Global Offensive'), ('GTAV', 'Grand Theft Auto V'), ('VALR', 'Valorant'), ('RAIN', 'Rainbow Six Siege')], max_length=4)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main.Group')),
                ('organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
