# Generated by Django 2.2.13 on 2020-08-01 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='organiser',
            new_name='player',
        ),
    ]
